[workspace]
members = [
    "apalache-itf",
    "apalache-itf-derive",
]

[workspace.dependencies]
itertools = "0.10"
num-bigint = { version = "0.4.3", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"
syn = "1"
proc-macro2 = "1"
quote = "1"
