[package]
name    = "itf"
version = "0.1.0"
edition = "2021"

[dependencies]
num-bigint = { version = "0.4", features = ["serde"] }
num-traits = { version = "0.2" }
serde      = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["raw_value"] }
